server {
    listen 8000;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location ~* \.(js|json|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf)$ {
        expires 1h;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}